### ISSUE TITLE
Input doesn't work

### ISSUE THREAD

**Issue by annethereshewent** [KieronJ/rpsx#15]
Input doesn't seem to work either using a controller or keyboard. I've tried on both MacOS and Windows and neither accepts any input on any game I've tried.

It does seem like SDL2 is accepting my button presses but the games don't do anything with it.

**Comment by KieronJ** [comment]
That's strange, haven't seen anything like that on my end.
Which game(s) did you see this in?

**Comment by annethereshewent** [comment]
Hey sorry for the late reply, but Final Fantasy VII and Castlevania Symphony of the Night are currently not working.

**Comment by KieronJ** [comment]
I took a look at this finally, thanks for raising it.
Very anticlimactic, but the game appears to only work in digital mode.

It might be worth making that the default mode instead of analogue.
