### ISSUE TITLE
Save and load emulator state

### ISSUE THREAD

**Issue by carlospzlz** [KieronJ/rpsx#4]
Is it possible to save the current state of the emulator to a file, so it can be loaded later?

I can see the function `load_psexe`, but I'm not entirely sure what it does, or can see any counterpart `save_psexe`.

**Comment by KieronJ** [comment]
Save states aren't supported currently I'm afraid.
The `load_psexe` function is related to directly loading a PlayStation executable instead of booting from a disc image.

**Comment by KieronJ** [comment]
There's an issue tracking save state implementation progress now. #5
Thanks for raising this as an issue. I probably wouldn't have gotten around to it otherwise. :)

**Comment by KieronJ** [comment]
Save state support is added by #6 :)
